[project]
name = "codealong"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.1",
    "jupyter>=1.1.1",
    "openai>=2.15.0",
    "python-dotenv>=1.2.1",
    "toyaikit>=0.0.9",
    "uv>=0.9.26",
]
